### ISSUE TITLE
Doesn't work against Puma master right now?

### ISSUE THREAD

**Issue by nateberkopec** [MSP-Greg/issue-pr-link#1]
I tried to do a ```ruby ../issue-pr-link/history_new_release.rb ../issue-pr-link/info.sample v5.6.5``` versus current master and got blank output:

```
## major.minor.patch / yyyy-mm-dd
```

Did I do something incorrect?

**Comment by MSP-Greg** [comment]
Let me have a look in a second...

**Comment by MSP-Greg** [comment]
> Did I do something incorrect?

No.  Maybe I did.  And I'm not sure whether a 'code' solution is possible.  The code assumes releases are done on the master branch, or it assumes that all the commits **after the date of the `5.6.5` release/tag** are what should be in the next 'release notes'.  But there are no commits yet, and the last couple of releases have been from the `5-6-stable` branch.  So, there are 'old' commits `master` that aren't in `5-6-stable`.

Some of the code is REST, some is GraphQL.  I'll look at the data to see if it's possible to determine what commits are in `master` than aren't in the `5-6-stable` branch.  Not.sure.  I.think.that.made.sense...

**Comment by MSP-Greg** [comment]
Element?

**Comment by nateberkopec** [comment]
> assumes that all the commits after the date of the 5.6.5 release/tag are what should be in the next 'release notes'

That's what I figured. I can work around by doing 5.6.4 and deleting what I released in 5.6.5. 👍

**Comment by MSP-Greg** [comment]
Might check 5.6.0, as there are quite a few features.  Haven't checked to see if any were moved to another category...
