### ISSUE TITLE
New "fine grained" Github Tokens aren't 40 characters

### ISSUE THREAD

**Issue by nateberkopec** [MSP-Greg/issue-pr-link#2]
Removing the check and everything still works just fine.

The new token I got was 93 characters, but I'm unsure if there's any guarantees there as to length.

**Comment by MSP-Greg** [comment]
Thanks.  I think I fixed it.  Code assumes 40 or more characters.

Happy New Year!

**Comment by nateberkopec** [comment]
Happy New Year! 🎉
